glyphs = {
    "nf-cod-account": "eb99",
    "nf-cod-activate_breakpoints": "ea97",
    "nf-cod-add": "ea60",
    "nf-cod-archive": "ea98",
    "nf-cod-arrow_both": "ea99",
    "nf-cod-arrow_down": "ea9a",
    "nf-c-arrow_left": "ea9b",
    "nf-cod-arrow_right": "ea9c",
    "nf-cod-arrow_small_down": "ea9d",
    "nf-cod-arrow_small_left": "ea9e",
    "nf-cod-arrow_small_right": "ea9f",
    "nf-cod-arrow_small_up": "eaa0",
    "nf-cod-arrow_swap": "ebcb",
    "nf-cod-arrow_up": "eaa1",
    "nf-cod-azure": "ebd8",
    "nf-cod-azure_devops": "ebe8",
    "nf-cod-beaker": "ea79",
    "nf-cod-beaker_stop": "ebe1",
    "nf-cod-bell": "eaa2",
    "nf-cod-bell_dot": "eb9a",
    "nf-cod-bold": "eaa3",
    "nf-cod-book": "eaa4",
    "nf-cod-bookmark": "eaa5",
    "nf-cod-bracket_dot": "ebe5",
}
